name: kreador-odoo-dev
services:
  # PostgreSQL Database (shared between versions)
  odoo17_db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo17
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./volumes/db/odoo17/data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    networks:
      - odoo_network
    profiles:
      - odoo17
    healthcheck:
      test: [CMD-SHELL, pg_isready -U odoo -d odoo17]
      interval: 10s
      timeout: 5s
      retries: 5
  odoo18_db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo18
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./volumes/db/odoo18/data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - odoo_network
    profiles:
      - odoo18
    healthcheck:
      test: [CMD-SHELL, pg_isready -U odoo -d odoo18]
      interval: 10s
      timeout: 5s
      retries: 5

  # Odoo 17 Development Environment
  odoo17:
    image: odoo:17
    depends_on:
      odoo17_db:
        condition: service_healthy
    environment:
      HOST: odoo17_db
      USER: odoo
      PASSWORD: odoo
    command: odoo -d odoo17 -i base --without-demo=all --dev=reload,qweb,werkzeug,xml
    volumes:
      - ./addons17:/mnt/extra-addons
      - ./config17:/etc/odoo
      - ./volumes/odoo17:/var/lib/odoo
    ports:
      - 8069:8069
    networks:
      - odoo_network
    profiles:
      - odoo17
    restart: unless-stopped

  # Odoo 18 Development Environment
  odoo18:
    image: odoo:18
    depends_on:
      odoo18_db:
        condition: service_healthy
    environment:
      HOST: odoo18_db
      USER: odoo
      PASSWORD: odoo
    command: odoo -d odoo18 -i base --without-demo=all --dev=reload,qweb,werkzeug,xml
    volumes:
      - ./addons18:/mnt/extra-addons
      - ./config18:/etc/odoo
      - ./volumes/odoo18:/var/lib/odoo
    ports:
      - 8070:8069
    networks:
      - odoo_network
    profiles:
      - odoo18
    restart: unless-stopped

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - odoo_network
    profiles:
      - tools

networks:
  odoo_network:
    driver: bridge