services:
  # PostgreSQL Database (shared between versions)
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - odoo_network

  # Odoo 17 Development Environment
  odoo17:
    image: odoo:17
    depends_on:
      - db
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./addons17:/mnt/extra-addons
      - ./config17:/etc/odoo
      - odoo17_data:/var/lib/odoo
    ports:
      - "8069:8069"
    networks:
      - odoo_network
    profiles:
      - odoo17

  # Odoo 18 Development Environment
  odoo18:
    image: odoo:18
    depends_on:
      - db
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./addons18:/mnt/extra-addons
      - ./config18:/etc/odoo
      - odoo18_data:/var/lib/odoo
    ports:
      - "8070:8069"
    networks:
      - odoo_network
    profiles:
      - odoo18

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - odoo_network
    profiles:
      - tools

volumes:
  postgres_data:
  odoo17_data:
  odoo18_data:

networks:
  odoo_network:
    driver: bridge